### ISSUE TITLE
Implement a database to keep track of player and crew histories. 

### ISSUE THREAD

**Issue by JettJengaGod** [JettJengaGod/scoresheetbot#7]

**Comment by JettJengaGod** [comment]
```
User:
  Id: int (doesn't change)
  Nickname: str (Track changes)
  discord_name: str (Track Changes)
  Crew: Crew (Track Changes)
  Roles: List[Role] (Track Changes)
  Watchlisted_till: Datetime (Don't track changes)
  join_cd_expiration: Optional[Datetime]
  ModNotes: Optional[Str] (Mods could write notes on users that would persist)
  Track: Role (Which track they are on, goal would be to auto reassign if they leave the server and come back)
  Cbs_played: int
  stocks_taken: int
  Characters_played_frequency: Tuple(Character, int) (Character, times played)
  mvps: int (Number of times mvp)
  best_cb: CrewBattle (Most stocks taken in a single CB)  


Crew:
  ID: int (doesn't change, wouldn't be related to the role id)
  Name: str (Track Changes)
  Tag: str (Track Changes)
  Rank: str (Track Changes)
  merit: int (Track Changes)
  Members: List[User] (Track Changes)
  Leaders: List[User] (Track Changes)
  Advisors: List[User] (Track Changes)
  Power_merge_slots: int (Idk how this actually works, but we can track it)
  Overflow: boolean (Shouldn't change, but we could track changes if need be)
  ModNotes: Optional[Str] (Mods could write notes on crews that would persist)
   Cb_record: (int,int) (Wins, Losses)
  Past_cbs: List[CrewBattle] (All of the previous crew battles this crew has played in)

CrewBattle: (Still figuring out how to store this one)
  ID: int 
  Link: str (Link to the scoresheetbot finished scoresheet)
  Winner: Crew
  Loser: Crew
  Final Score: int (Number of stocks winning team had left)
  Winner MVP: User
  Loser MVP: User
  Matches: List[Match] (Tracks each individual match in the crew battle

Match:
  P1: User
  P2: User
  P1_char: Character
  P2_char: Character
  P1_taken: int
  P2_taken: int
  winner: User
  Loser: User
  
```
